### ISSUE TITLE
Change Error_Partition attributes to String

### ISSUE THREAD

**Issue by NorbertKrupa** [dcaton/Hubitat#4]
https://github.com/dcaton/Hubitat/blob/828edf0b3003a51e19a40b6b32b21488d1f80c0c/QolSysIQPanel/QolSysIQ-Panel.groovy#L58

When trying to create a trigger via Rule Machine, an error is thrown that `Error_Partition_*` is `TEXT`:

![49a7f3669291dfea4dc85841c6cf3a42f411b317](https://user-images.githubusercontent.com/3281285/188675212-0d91b9ab-0df6-43d5-a129-8830137c955b.png)

According to [this post](https://community.hubitat.com/t/notifications-for-attributes/100409/6?u=norbert.krupa_hubita), it should be a `STRING`.

**Comment by dcaton** [comment]
Fixed, thank you.
