### ISSUE TITLE
Alarm Arming & Disarming Not Visible in HomeKit Integration

### ISSUE THREAD

**Issue by alfredopisano** [dcaton/Hubitat#6]
Hello, Following the instructions i was able to get the drivers installed using Package Manager (Custom User App). All the sensors of the IQPanel show up nicely in HomeKit, but the alarm panel doesnt. I turned on all the options in the Alaram System Virtual Device and till not visible in HomeKit. Did i miss something? Has anyone else seen this?

**Comment by dcaton** [comment]
Sorry, can't help with HomeKit, I know nothing about it. Your best bet is to ask in the Hubitat forums. 

https://community.hubitat.com/
